#!/usr/bin/env bash

if [[ $1 == "" ]]; then
    echo "usage: ./extract patch"
    exit 1
fi

if [[ ! -f "/usr/local/bin/smv" ]]; then
    echo "error: Could not find SmartVersion executable in /usr/local/bin."
    exit 1
fi

if [[ ! -f "$1" ]]; then
    echo "error: Could not find SmartVersion patch."
    exit 1
fi

if ! "/usr/bin/env" "smv" x $1 -br .; then
    echo "error: Could not extract SmartVersion patch."
    exit 1
fi

echo "success: Successfully extracted SmartVersion patch."
exit 0
