#!/usr/bin/env bash

if [[ ! -f "/usr/local/bin/smv" ]]; then
    echo "error: Could not find SmartVersion executable in /usr/local/bin."
    exit 1
fi

success=0
error=0

for f in ./*.svf; do
    if "/usr/bin/env" "smv" x "$f" -br .; then
        (( success+=1 ))
    else
        (( error+=1 ))
    fi
done

# doesn't work yet
if [[ $error == 0 ]]; then
    echo "success: Successfully extracted $success SmartVersion patches."
    exit 0
else
    echo "error: Successfully extracted $success SmartVersion patches and encountered $error errors."
    exit 1
fi
