#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
    echo "error: Insufficient permissions."
    exit 1
fi

LSCPU_OUTPUT=$(lscpu)
if [[ $LSCPU_OUTPUT =~ "x86_64" ]]; then
    CPU_ARCHITECTURE="x64"
elif [[ $LSCPU_OUTPUT =~ "i386" || $LSCPU_OUTPUT =~ "i486" || $LSCPU_OUTPUT =~ "i586" || $LSCPU_OUTPUT =~ "i686" ]]; then
    CPU_ARCHITECTURE="x86"
else
    echo "error: SmartVersion is not compatible with your processor architecture."
    exit 1
fi

if ! wget "https://www.smartversion.com/smartvs38_linux_$CPU_ARCHITECTURE.zip" -O "smartvs38_linux_$CPU_ARCHITECTURE.zip"; then
    echo "error: Could not download SmartVersion package."
    exit 1
fi

if ! unzip -o "smartvs38_linux_$CPU_ARCHITECTURE.zip"; then
    echo "error: Could not unzip SmartVersion package."
    exit 1
fi

if ! cp "smv" "/usr/local/bin"; then
    echo "error: Could not copy SmartVersion executable to /usr/local/bin/smv."
    exit 1
fi

echo "success: Successfully installed SmartVersion executable to /usr/local/bin/smv."
exit 0
