#!/usr/bin/env bash

if [[ ! -f "/usr/bin/smv" ]]; then
    echo "error: Could not find SmartVersion executable in /usr/bin."
    exit 1
fi

if [[ $1 == "" ]]; then
    echo "usage: ./patch-all source-file"
    exit 1
fi

success=0
error=0

if [[ ! -f "$1" ]]; then
    echo "error: Could not find source file."
    exit 1
fi

# -nbhashbits 24 -compressratio 192: based on https://forums.mydigitallife.net/threads/smartversion-tools-scripts.79415/page-14#post-1599203
for f in *${1##*.}; do
    if [[ "$f" != "$1" ]]; then
        "/usr/bin/env" "smv" BuildPatch "${1%.*}_to_${f%.*}.svf" $1 "$f" -nbhashbits 24 -compressratio 192 -sha1 -sha256
        if [[ $? == 0 ]]; then
            let "success+=1"
        else
            let "error+=1"
        fi
    fi
done

if [[ $error == 0 ]]; then
    echo "success: Successfully patched $success files."
    exit 0
else
    echo "error: Successfully patched $success files and encountered $error errors."
    exit 1
fi
