#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
    echo "error: Insufficient permissions."
    exit 1
fi

if [[ ! -f "/usr/local/bin/smv" ]]; then
    echo "error: Could not find SmartVersion executable in /usr/local/bin."
    exit 1
fi

if ! rm "/usr/local/bin/smv"; then
    echo "error: Could not remove SmartVersion executable from /usr/local/bin/smv."
    exit 1
fi

echo "success: Successfully uninstalled SmartVersion executable from /usr/local/bin/smv."
exit 0
